### ISSUE TITLE
Storybook working with typescript components

### ISSUE THREAD

**Issue by willemolding** [holochain/holochain-ui#97]

**Comment by willemolding** [comment]
storybook in the typescript-migration branch now has the ability to work for typescript components as demonstrated by the happs component. It also ignores all of the old .js storybook files which is useful for until they are migrated

**Comment by willemolding** [comment]
Can now run javascript and typescript stories in the same storybook. This should make transitioning a breeze!

**Comment by philipbeadle** [comment]
Yep love it.
